import type { Metadata } from "next";
import "./globals.css";
import ProgressBarClient from "@/components/ProgressBarClient";

export const metadata: Metadata = {
  title: "Airbnb-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProgressBarClient />
        {children}
      </body>
    </html>
  );
}
